// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoZMqERB1q9j_jh6P3jzEnMD32tCo9BPc',
    appId: '1:531284392680:web:0a02396f24bcf70fa9a75d',
    messagingSenderId: '531284392680',
    projectId: 'aquaroot-9e785',
    authDomain: 'aquaroot-9e785.firebaseapp.com',
    storageBucket: 'aquaroot-9e785.firebasestorage.app',
    measurementId: 'G-EFX8GX33W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6MTzjhXLaz5pPOv26nZLyUjtonQy9k1Y',
    appId: '1:531284392680:android:e399147ec2860e5aa9a75d',
    messagingSenderId: '531284392680',
    projectId: 'aquaroot-9e785',
    storageBucket: 'aquaroot-9e785.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjy86ykTh_bBfmp2_k1VhU7wQh8oFCBms',
    appId: '1:531284392680:ios:f59fc6f16ec4116da9a75d',
    messagingSenderId: '531284392680',
    projectId: 'aquaroot-9e785',
    storageBucket: 'aquaroot-9e785.firebasestorage.app',
    iosClientId: '531284392680-nb3mk01d570f2jvqtjhbskr8ctj4a9j5.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquaroot',
  );
}
